#yml文件不能使用制表符空格tab，只能使用普通空格表示缩进
#设置值 使用:空格(值)
server:
  port: 80
  
  
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1/c83-s2-phjx-damai?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: hjx199836  
      driver-class-Name: com.mysql.cj.jdbc.Driver
      
#邮件发送 yml配置规则:如果某个阶段有重复配置情况，必须要合并
   mail:
      #邮箱服务器地址
      host: smtp.qq.com
      #用户名
      username: 1532131020@qq.com
      #密码
      password: fkvxruagsupjhhfc
      default-encoding: UTF-8
      
#日志配置
logging:
   level:
     com:
       yc:
          C83S3PhjxSpringBoot:
             dao: debug
             web: warn
             
             
#以谁来发送邮件==》用户自定义的属性
mail:
  fromMail: 
     addr: 1532131020@qq.com
     
     
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
      


   
  
