server:
  port: 80
  
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1/c83-s3-phjx-blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: hjx199836  
      driver-class-Name: com.mysql.cj.jdbc.Driver
      
      
logging:
   level:
     com:
        yc:
          C83S3Phjxblog: debug
